### ISSUE TITLE
预编译好的 alone_so_lib 目录下的 armeabi-v7a so  在 4.x 设备上崩溃 

### ISSUE THREAD

**Issue by shaobin0604** [shoyu666/bsdiffAndroidDemo#1]
c1d9ba56dac57bcbf3e2a1aaed34198cbd70d19d 解决了这 4.x 设备上的兼容问题，但 alone_so_lib 目录下的 so 没有更新

**Comment by shoyu666** [comment]
@shaobin0604  才看到
4.x 的手机么？用 armeabi的看看 
可以把错误日志贴出来看看
